[package]
name = "vkinfo"
version = "0.1.0"
authors = ["Michael Zoech <michi.zoech@gmail.com>"]

[dependencies]
bitflags = "1.0.1"
libloading = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"